remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: sourceds
description: watching airplanes, studying computer science, and goofing around - all while doing military paperwork
logo: /assets/alos.webp
